Update main_mindmingleexe202.yml

diff --git a/.github/workflows/main_mindmingleexe202.yml b/.github/workflows/main_mindmingleexe202.yml
--- a/.github/workflows/main_mindmingleexe202.yml
+++ b/.github/workflows/main_mindmingleexe202.yml
@@ -22,15 +22,15 @@ jobs:
         uses: actions/setup-dotnet@v4
         with:
           dotnet-version: '8.x'
-          
-      - name: Debug published files
-        run: dir "${{env.DOTNET_ROOT}}/myapp"
 
       - name: Build with dotnet
         run: dotnet build --configuration Release
-
+          
       - name: dotnet publish
         run: dotnet publish -c Release -o "${{env.DOTNET_ROOT}}/myapp"
+        
+      - name: Debug publish output
+        run: dir "${{env.DOTNET_ROOT}}/myapp" || echo "Directory not found or empty"
 
       - name: Upload artifact for deployment job
         uses: actions/upload-artifact@v4
