Update main_mindmingleexe202.yml

diff --git a/.github/workflows/main_mindmingleexe202.yml b/.github/workflows/main_mindmingleexe202.yml
--- a/.github/workflows/main_mindmingleexe202.yml
+++ b/.github/workflows/main_mindmingleexe202.yml
@@ -24,19 +24,19 @@ jobs:
           dotnet-version: '8.x'
 
       - name: Build with dotnet
-        run: dotnet build --configuration Release
+        run: dotnet build ./MindMingle/API/API.csproj --configuration Release
           
       - name: dotnet publish
-        run: dotnet publish -c Release -o "${{env.DOTNET_ROOT}}/myapp"
+        run: dotnet publish -c Release -o "${{env.DOTNET_ROOT}}/MindMingle/API/API.csproj"
         
       - name: Debug publish output
-        run: dir "${{env.DOTNET_ROOT}}/myapp" || echo "Directory not found or empty"
+        run: dir "${{env.DOTNET_ROOT}}/./MindMingle/API" || echo "Directory not found or empty"
 
       - name: Upload artifact for deployment job
         uses: actions/upload-artifact@v4
         with:
           name: .net-app
-          path: ${{env.DOTNET_ROOT}}/myapp
+          path: ${{env.DOTNET_ROOT}}/MindMingle/API/API.csproj
 
   deploy:
     runs-on: windows-latest
